
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT

paths:
  /:
    get:
      responses:
        '200':
           description: OK


components:
  schemas:
    InitializeConnectionResponse: # AGGREGATE-NAME
      type: object  # SUPPORTED-OPENAPI-TYPE
      description: 'Initial connection response.' # TEXT
      x-aggregate-version: v1.0.0  # VERSION-STRING
      properties:
        DeviceId: { type: string }
        RequestApproved: { type: boolean }
      x-meta-data:
        versions:
          v1.0.0: # VERSION-STRING
            properties:
              DeviceId:
                x-version-ref: 'v1.0.0'  # VERSION-STRING
